# Generated by Django 6.0.3 on 2026-04-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="cursos/"),
        ),
    ]
