# Generated by Django 6.0.3 on 2026-03-31 15:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("url_lusofona", models.URLField()),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="docentes/"),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "Docente",
                "verbose_name_plural": "Docentes",
            },
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("sigla", models.CharField(max_length=20)),
                (
                    "grau",
                    models.CharField(
                        choices=[
                            ("licenciatura", "Licenciatura"),
                            ("mestrado", "Mestrado"),
                            ("doutoramento", "Doutoramento"),
                            ("ctesp", "CTeSP"),
                        ],
                        max_length=20,
                    ),
                ),
                ("area_cientifica", models.CharField(max_length=200)),
                ("duracao_anos", models.IntegerField()),
                ("ects_total", models.IntegerField()),
                ("descricao", models.TextField()),
                ("url_lusofona", models.URLField()),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="licenciatura/"),
                ),
                ("ano_inicio", models.IntegerField()),
            ],
            options={
                "verbose_name": "Licenciatura",
                "verbose_name_plural": "Licenciaturas",
            },
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("entidade_relacionada", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "fotografia",
                    models.ImageField(blank=True, null=True, upload_to="makingof/"),
                ),
                ("data", models.DateField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("decisao", "Decisão"),
                            ("erro", "Erro"),
                            ("correcao", "Correção"),
                            ("evolucao", "Evolução"),
                        ],
                        max_length=20,
                    ),
                ),
                ("uso_ia", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Making Of",
                "verbose_name_plural": "Making Of",
            },
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("linguagem", "Linguagem de Programação"),
                            ("framework", "Framework"),
                            ("biblioteca", "Biblioteca"),
                            ("ferramenta", "Ferramenta"),
                            ("base_dados", "Base de Dados"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField()),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
                ("url_website", models.URLField(blank=True)),
                (
                    "nivel_interesse",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("ano_inicio", models.IntegerField()),
                ("em_uso", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tecnologia",
                "verbose_name_plural": "Tecnologias",
            },
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("conceitos_aplicados", models.TextField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="projetos/"),
                ),
                ("video_demo", models.URLField(blank=True)),
                ("repositorio_github", models.URLField(blank=True)),
                ("data_realizacao", models.DateField()),
                ("classificacao", models.DecimalField(decimal_places=2, max_digits=4)),
                ("destaque", models.BooleanField(default=False)),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="projetos", to="portfolio.tecnologia"
                    ),
                ),
            ],
            options={
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
            },
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("instituicao", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("curso", "Curso"),
                            ("workshop", "Workshop"),
                            ("certificacao", "Certificação"),
                            ("mooc", "MOOC"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField()),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                (
                    "certificado",
                    models.ImageField(blank=True, null=True, upload_to="formacoes/"),
                ),
                ("url", models.URLField(blank=True)),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="formacoes", to="portfolio.tecnologia"
                    ),
                ),
            ],
            options={
                "verbose_name": "Formação",
                "verbose_name_plural": "Formações",
            },
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("tecnica", "Técnica"),
                            ("transversal", "Transversal"),
                            ("soft", "Soft Skill"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField()),
                (
                    "nivel",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "projetos",
                    models.ManyToManyField(
                        blank=True, related_name="competencias", to="portfolio.projeto"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="competencias",
                        to="portfolio.tecnologia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competência",
                "verbose_name_plural": "Competências",
            },
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("ano", models.IntegerField()),
                ("autor", models.CharField(max_length=200)),
                ("orientador", models.CharField(max_length=200)),
                ("url_repositorio", models.URLField(blank=True)),
                ("url_documento", models.URLField(blank=True)),
                ("destaque", models.BooleanField(default=False)),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="tfcs", to="portfolio.tecnologia"
                    ),
                ),
            ],
            options={
                "verbose_name": "TFC",
                "verbose_name_plural": "TFCs",
            },
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("sigla", models.CharField(max_length=20)),
                ("ano_curricular", models.IntegerField()),
                (
                    "semestre",
                    models.IntegerField(
                        choices=[(1, "1º Semestre"), (2, "2º Semestre")]
                    ),
                ),
                ("ects", models.IntegerField()),
                ("descricao", models.TextField()),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="ucs/")),
                ("codigo", models.CharField(max_length=20)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "docentes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="unidades_curriculares",
                        to="portfolio.docente",
                    ),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades_curriculares",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidade Curricular",
                "verbose_name_plural": "Unidades Curriculares",
            },
        ),
        migrations.AddField(
            model_name="projeto",
            name="unidade_curricular",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projetos",
                to="portfolio.unidadecurricular",
            ),
        ),
    ]
