# Generated by Django 6.0.4 on 2026-04-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tecnologia",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("frontend", "Frontend"),
                    ("backend", "Backend"),
                    ("base_dados", "Base de Dados"),
                    ("storage", "Storage"),
                    ("outros", "Outros"),
                ],
                max_length=20,
            ),
        ),
    ]
