# Generated by Django 6.0.5 on 2026-05-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_tecnologia_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="url_documento",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="url_repositorio",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
