# Generated by Django 6.0.5 on 2026-05-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_tfc_url_documento_alter_tfc_url_repositorio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="orientador",
            field=models.CharField(max_length=500),
        ),
    ]
