# Generated by Django 6.0.5 on 2026-05-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_tfc_orientador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="orientador",
            field=models.TextField(),
        ),
    ]
